# 服务器配置
server:
  port: 8087
  session:
    timeout: 1800
    
spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.31:3306/loan?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: null
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
    timeout: 5000
    
  resources:
    static-locations:
    - classpath:/static/
    - classpath:/public/
    
datasource:
  write:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.31:3306/loan?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
  read:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.31:3307/loan?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

statViewServlet:
  initParameter:
    # 白名单Ip
    allow: 192.168.3.31
    # 黑名单Ip
    deny: 192.168.1.100
    loginUsername: admin
    loginPassword: 123
    resetEnable: false
    
logging:
  file: E:/logs/manage/logback_spring.log
  level:
    root: info

