spring:
  profiles:
    active:
    - dev
  freemarker:
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.#
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 关闭Spring安全基本认证    
security:
  basic:
    enabled: false