server:
  port: 8088
  session:
    timeout: 1800
spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: root123
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
    timeout: 5000
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/static/
    - classpath:/public/
    - http://127.0.0.1:8082/
service:
  sms:
    password: 123456
    username: admin
    apikey: admin123
    url: http://127.0.0.1:8081/sms/send.do
  email:
    username: admin@qq.com
    password: 123456
    host: 127.0.0.1
    url: http://127.0.0.1:8081/email/verify.do

# 微信支付相关配置
pay:
  wechat:
    appId: wx0281f93238d254a1
    mchId: 1484366432
    mchKey: nl089QrXQXZotDrhN25v8jddlz2MRPZh
    notifyUrl: http://192.168.3.31/onlineRecharge/wechatPayCallBack
    wechatPayUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
    
upload:
  path:
    img: E:/www/upload/
logging:
  file: E:/logs/platform/logback_spring.log
  level:
    root: info