spring:
  profiles:
    active:
    - dev
    
  freemarker:
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8 # 中国时区
    date-format: yyyy-MM-dd HH:mm:ss

      
      
