spring:
  profiles:
    active:
    - dev

---

#服务器相关设置
server:
  port: 8081
  session:
    timeout: 1800

spring:
  profiles: dev
  #数据源 druid 连接池
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: root123
  #freemarker 配置
  freemarker:
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  #jpa相关配置   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   #Redis相关配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      #连接池最大空闲连接
      max-idle: 8
      #连接池最小空闲连接
      min-idle: 0
      #连接池最大连接数
      max-active: 8
      max-wait: 1
    #连接超时时间
    timeout: 5000
  #文件上传
  http:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  # 静态资源地址
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/static/
    - classpath:/public/
    - http://localhost:8082/
    
service:
  # 短信服务相关配置
  sms:
    password: 123456
    username: admin
    apikey: admin123
    url: http://localhost:8081/sms/send.do
  # 邮箱服务相关配置  
  email:
    username: admin@qq.com
    password: 123456
    host: localhost
    url: http://localhost:8081/email/verify.do

#文件上传相关配置
upload:
  path:
    img: E:/www/upload/

#日志配置
logging:
  file: E:/logs/loan/logback_spring.log
  level:
    root: info
    #org.hibernate: info
    #输出sql传入参数相关信息
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
    #输出sqlselect出来的相关信息
    #org.hibernate.type.descriptor.sql.BasicExtractor: trace
    
#关闭spring security的默认登录    
security:
  basic:
    enabled: false