spring:
  profiles:
    active:
    - dev
  #freemarker 配置
  freemarker:
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.#
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss    
    
---

#服务器相关设置
server:
  port: 8080
  session:
    timeout: 1800

spring:
  profiles: dev
  #数据源 druid 连接池
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: root123
    data:
    #- classpath:quartz_tables.sql
  #jpa相关配置   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Redis相关配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 
    pool:
      #连接池最大空闲连接
      max-idle: 8
      #连接池最小空闲连接
      min-idle: 0
      #连接池最大连接数
      max-active: 8
      max-wait: 1
    #连接超时时间
    timeout: 5000
  #静态资源地址
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/static/
    - classpath:/public/
    #图片服务器地址
    - http://localhost:8082/

#日志配置
logging:
  file: E:/logs/admin/logback_spring.log
  level:
    root: info

#关闭spring security的默认登录    
security:
  basic:
    enabled: false