server:
  port: 8080
  session:
    timeout: 1800

spring:
  freemarker:
    expose-session-attributes: true
    suffix: .html
    settings:
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
#数据源配置    
datasource:
  write:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/key?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  read:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/key?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

    