spring:
  profiles:
    active:
    - dev
  #freemarker 配置
  freemarker:
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.#
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  #jpa相关配置   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#关闭spring security的默认登录    
security:
  basic:
    enabled: false    
