server:
  port: 8080
        
datasource:
  master:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  slaveOne:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
        
logging:
  level:
    com.example.mapper: debug #mybatis sql执行日志

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: null
    timeout: 60
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.qq.com
    username: 719748187@qq.com
    password: fpnqgibsoohybdgh
          
mybatis:
  configuration:
    cache-enabled: true #开启二级缓存
