logging:
  level:
    com.example.mapper: debug #mybatis sql执行日志

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  profiles:
    active:
    - dev
    
mybatis:  mapper-locations:  - classpath:mapper/*Mapper.xml
    